### PR TITLE
Updated additional editorial changes from review comments to notebook

### PR DESCRIPTION
**Pull request by asurve**

### CODE REVIEW

**Comment by asurve** [comment]
@MadisonJMyers Please review notebook changes you requested in issue #9

**Review by stevemar — APPROVED** [review]
i'm oK, will wait for @MadisonJMyers to review before merging

**Review by MadisonJMyers — APPROVED** [review]
LGTM!

**Comment by asurve** [comment]
Thanks @stevemart & @MadisonJMyers

**Pull request merged**
